CREATE TABLE CHUYENDI
(
	MACD INT NOT NULL  IDENTITY,
	TENCD NVARCHAR(50),
	TRANGTHAI BIT,
	NGAYDI DATE,
	NGAYKT DATE,
	DODAI INT,

	CONSTRAINT PK_CHUYENDI
	PRIMARY KEY(MACD)
)

CREATE TABLE THANHVIEN
(
	MATV INT NOT NULL IDENTITY,
	MACD INT,
	HOTEN NVARCHAR(50),
	NHATKY NVARCHAR(MAX),
	SDT VARCHAR(15),
	TRANGTHAI BIT,
	

	CONSTRAINT PK_THANHVIEN
	PRIMARY KEY(MATV,MACD)
)

CREATE TABLE DIADIEM
(
	MADD INT NOT NULL IDENTITY,
	MACD INT,
	STT INT,
	TENDD NVARCHAR(50),

	CONSTRAINT PK_DIADIEM
	PRIMARY KEY(MADD,MACD,STT)
)

CREATE TABLE HINHANH
(
	MACD INT,
	HINHANH VARCHAR(100),
)

CREATE TABLE THUCHI
(
	MATV INT,
	MACD INT,
	TENKHOANCHI NVARCHAR(100),
	TIEN INT,
	

	CONSTRAINT PK_THUCHI
	PRIMARY KEY(MACD,TENKHOANCHI)
)

ALTER TABLE THANHVIEN ADD CONSTRAINT FK_THANHVIEN_CHUYENDI FOREIGN KEY(MACD) REFERENCES CHUYENDI(MACD)

ALTER TABLE DIADIEM ADD CONSTRAINT FK_DIADIEM_CHUYENDI FOREIGN KEY (MACD) REFERENCES CHUYENDI(MACD)

ALTER TABLE HINHANH ADD CONSTRAINT FK_HINHANH_CHUYENDI FOREIGN KEY(MACD) REFERENCES CHUYENDI(MACD)

ALTER TABLE THUCHI ADD CONSTRAINT FK_THUCHI_CHUYENDI FOREIGN KEY (MACD) REFERENCES CHUYENDI(MACD)

ALTER TABLE THUCHI ADD CONSTRAINT FK_THUCHI_THANHVIEN FOREIGN KEY (MATV,MACD) REFERENCES THANHVIEN(MATV,MACD)

drop table THUCHI
ALTER TABLE THUCHI DROP CONSTRAINT FK_THUCHI_CHUYENDI